# Generated by Django 4.1.4 on 2022-12-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__full_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
