# Generated by Django 4.1.4 on 2023-01-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeaddress',
            old_name='home_price',
            new_name='shipping_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order'),
        ),
    ]
