# Generated by Django 4.1.4 on 2023-01-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_home_price_homeaddress_shipping_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
