# Generated by Django 4.1.4 on 2023-01-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_homeaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeaddress',
            name='shipping_price',
        ),
    ]
